services:
  app_proxy:
    environment:
      APP_HOST: alistairg-ultrafeeder_server_1
      APP_PORT: 80

  server:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder:latest
    restart: unless-stopped
    tmpfs:
      - /run/readsb
      - /var/log
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - TZ=${TZ:-UTC}
      - READSB_LAT=${SITE_LAT}
      - READSB_LON=${SITE_LON}
      - READSB_ALT=${SITE_ALT_M:-50}m
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - UUID=${ULTRAFEEDER_UUID}
      - ULTRAFEEDER_CONFIG=${ULTRAFEEDER_CONFIG}
      - READSB_NET_BEAST_OUTPUT_PORT=30005
      - READSB_NET_BEAST_REDUCE_INTERVAL=0.5
    volumes:
      - ${APP_DATA_DIR}/globe_history:/var/globe_history
      - ${APP_DATA_DIR}/graphs1090:/var/lib/collectd

  piaware:
    image: ghcr.io/sdr-enthusiasts/docker-piaware:latest
    restart: unless-stopped
    profiles: [piaware]
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    environment:
      - TZ=${TZ:-UTC}
      - LAT=${SITE_LAT}
      - LONG=${SITE_LON}
      - FEEDER_ID=${PIAWARE_FEEDER_ID}
      - BEASTHOST=server
      - MLAT=true
      - MLATRESULTS=true
    depends_on:
      - server

  fr24feed:
    image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest
    restart: unless-stopped
    profiles: [fr24]
    environment:
      - TZ=${TZ:-UTC}
      - BEASTHOST=server
      - FR24KEY=${FR24_KEY}
      - MLAT=yes
    depends_on:
      - server
