services:
  app_proxy:
    environment:
      APP_HOST: alistairg-signalk_server_1
      APP_PORT: 3000

  server:
    image: signalk/signalk-server:latest
    restart: unless-stopped
    init: true
    user: "1000:1000"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${APP_DATA_DIR}:/home/node/.signalk